# 异常

Dart 提供 Exception 和 Error 来进行错误提示，但 Dart 中可以抛出任何除了`null`之外的值。

## Throw

```dart
throw FormatException('Expected at least 1 section');
```

也可以直接抛出字面量

```dart
throw 'Out of llamas!';
```

## Catch

捕获异常我们就可以处理异常

```dart
try {
  breedMoreLlamas();
} on OutOfLlamasException {
  // A specific exception
  buyMoreLlamas();
} on Exception catch (e) {
  // Anything else that is an exception
  print('Unknown exception: $e');
} catch (e) {
  // No specified type, handles all
  print('Something really unknown: $e');
}
```

你可以为`catch`指定2个参数，分别是被抛出的对象和 StackTrace

```dart
try {
  // ···
} on Exception catch (e) {
  print('Exception details:\n $e');
} catch (e, s) {
  print('Exception details:\n $e');
  print('Stack trace:\n $s');
}
```

要处理部分异常，但要继续传播，则使用`rethrow`关键词

```dart
void misbehave() {
  try {
    dynamic foo = true;
    print(foo++); // Runtime error
  } catch (e) {
    print('misbehave() partially handled ${e.runtimeType}.');
    rethrow; // Allow callers to see the exception.
  }
}

void main() {
  try {
    misbehave();
  } catch (e) {
    print('main() finished handling ${e.runtimeType}.');
  }
}
```

## Finally

无论是否捕获异常，走的哪个捕获分支，最后都会走 finally 块

```dart
try {
  breedMoreLlamas();
} catch (e) {
  print('Error: $e'); // Handle the exception first.
} finally {
  cleanLlamaStalls(); // Then clean up.
}
```